//
// auto-generated by ops.py
//
//header
#define OPS_API 2
#define OPS_3D
#ifdef __cplusplus
#include "ops_lib_cpp.h"
#endif
#ifdef OPS_MPI
#include "ops_mpi_core.h"
#endif
#include "ops_cuda_rt_support.h"
// global constants
extern int block0np0;
extern int block0np1;
extern int block0np2;
extern double Delta0block0;
extern double Delta1block0;
extern double Delta2block0;
extern int niter;
extern double dt;
extern double Minf;
extern double gama;
extern double Pr;
extern double Re;
extern double inv_0;
extern double inv_1;
extern double inv_2;
extern double inv_3;
extern double inv_4;
extern double inv_5;
extern double rc6;
extern double rcinv7;
extern double rc8;
extern double rc9;
extern double rcinv10;
extern double rcinv11;
extern double rc12;
extern double rc13;
extern double rc14;
extern double rc15;
extern double rc16;
extern double rc17;
extern double rc18;
extern double rc19;
extern double rc20;
extern double rc21;
extern double rc22;
extern double rc23;
extern double rc24;
extern double rc25;
extern double rc26;
extern double rc27;
extern double rc28;
extern double rc29;
extern double rc30;
extern double rc31;
extern double rc32;
extern double rc33;
extern double rc34;
extern double rc35;
extern double rc36;
extern double rc37;
extern double rc38;
