//
// auto-generated by ops.py
//

int xdim0_opensbliblock00Kernel037;
int ydim0_opensbliblock00Kernel037;
int xdim1_opensbliblock00Kernel037;
int ydim1_opensbliblock00Kernel037;
int xdim2_opensbliblock00Kernel037;
int ydim2_opensbliblock00Kernel037;
int xdim3_opensbliblock00Kernel037;
int ydim3_opensbliblock00Kernel037;
int xdim4_opensbliblock00Kernel037;
int ydim4_opensbliblock00Kernel037;
int xdim5_opensbliblock00Kernel037;
int ydim5_opensbliblock00Kernel037;
int xdim6_opensbliblock00Kernel037;
int ydim6_opensbliblock00Kernel037;
int xdim7_opensbliblock00Kernel037;
int ydim7_opensbliblock00Kernel037;
int xdim8_opensbliblock00Kernel037;
int ydim8_opensbliblock00Kernel037;
int xdim9_opensbliblock00Kernel037;
int ydim9_opensbliblock00Kernel037;
int xdim10_opensbliblock00Kernel037;
int ydim10_opensbliblock00Kernel037;
int xdim11_opensbliblock00Kernel037;
int ydim11_opensbliblock00Kernel037;
int xdim12_opensbliblock00Kernel037;
int ydim12_opensbliblock00Kernel037;


//user function



void opensbliblock00Kernel037_c_wrapper(
  double * restrict u2_B0_p,
  double * restrict rhoE_B0_p,
  double * restrict rho_B0_p,
  double * restrict p_B0_p,
  double * restrict rhou1_B0_p,
  double * restrict rhou0_B0_p,
  double * restrict rhou2_B0_p,
  double * restrict wk40_B0_p,
  double * restrict wk43_B0_p,
  double * restrict wk41_B0_p,
  double * restrict wk39_B0_p,
  double * restrict wk42_B0_p,
  double * restrict wk44_B0_p,
  int x_size, int y_size, int z_size) {
  #pragma omp parallel for
  for ( int n_z=0; n_z<z_size; n_z++ ){
    for ( int n_y=0; n_y<y_size; n_y++ ){
      for ( int n_x=0; n_x<x_size; n_x++ ){
        const ptr_double u2_B0 = { u2_B0_p + n_x*1 + n_y * xdim0_opensbliblock00Kernel037*1 + n_z * xdim0_opensbliblock00Kernel037 * ydim0_opensbliblock00Kernel037*1, xdim0_opensbliblock00Kernel037, ydim0_opensbliblock00Kernel037};
        const ptr_double rhoE_B0 = { rhoE_B0_p + n_x*1 + n_y * xdim1_opensbliblock00Kernel037*1 + n_z * xdim1_opensbliblock00Kernel037 * ydim1_opensbliblock00Kernel037*1, xdim1_opensbliblock00Kernel037, ydim1_opensbliblock00Kernel037};
        const ptr_double rho_B0 = { rho_B0_p + n_x*1 + n_y * xdim2_opensbliblock00Kernel037*1 + n_z * xdim2_opensbliblock00Kernel037 * ydim2_opensbliblock00Kernel037*1, xdim2_opensbliblock00Kernel037, ydim2_opensbliblock00Kernel037};
        const ptr_double p_B0 = { p_B0_p + n_x*1 + n_y * xdim3_opensbliblock00Kernel037*1 + n_z * xdim3_opensbliblock00Kernel037 * ydim3_opensbliblock00Kernel037*1, xdim3_opensbliblock00Kernel037, ydim3_opensbliblock00Kernel037};
        const ptr_double rhou1_B0 = { rhou1_B0_p + n_x*1 + n_y * xdim4_opensbliblock00Kernel037*1 + n_z * xdim4_opensbliblock00Kernel037 * ydim4_opensbliblock00Kernel037*1, xdim4_opensbliblock00Kernel037, ydim4_opensbliblock00Kernel037};
        const ptr_double rhou0_B0 = { rhou0_B0_p + n_x*1 + n_y * xdim5_opensbliblock00Kernel037*1 + n_z * xdim5_opensbliblock00Kernel037 * ydim5_opensbliblock00Kernel037*1, xdim5_opensbliblock00Kernel037, ydim5_opensbliblock00Kernel037};
        const ptr_double rhou2_B0 = { rhou2_B0_p + n_x*1 + n_y * xdim6_opensbliblock00Kernel037*1 + n_z * xdim6_opensbliblock00Kernel037 * ydim6_opensbliblock00Kernel037*1, xdim6_opensbliblock00Kernel037, ydim6_opensbliblock00Kernel037};
        ptr_double wk40_B0 = { wk40_B0_p + n_x*1 + n_y * xdim7_opensbliblock00Kernel037*1 + n_z * xdim7_opensbliblock00Kernel037 * ydim7_opensbliblock00Kernel037*1, xdim7_opensbliblock00Kernel037, ydim7_opensbliblock00Kernel037};
        ptr_double wk43_B0 = { wk43_B0_p + n_x*1 + n_y * xdim8_opensbliblock00Kernel037*1 + n_z * xdim8_opensbliblock00Kernel037 * ydim8_opensbliblock00Kernel037*1, xdim8_opensbliblock00Kernel037, ydim8_opensbliblock00Kernel037};
        ptr_double wk41_B0 = { wk41_B0_p + n_x*1 + n_y * xdim9_opensbliblock00Kernel037*1 + n_z * xdim9_opensbliblock00Kernel037 * ydim9_opensbliblock00Kernel037*1, xdim9_opensbliblock00Kernel037, ydim9_opensbliblock00Kernel037};
        ptr_double wk39_B0 = { wk39_B0_p + n_x*1 + n_y * xdim10_opensbliblock00Kernel037*1 + n_z * xdim10_opensbliblock00Kernel037 * ydim10_opensbliblock00Kernel037*1, xdim10_opensbliblock00Kernel037, ydim10_opensbliblock00Kernel037};
        ptr_double wk42_B0 = { wk42_B0_p + n_x*1 + n_y * xdim11_opensbliblock00Kernel037*1 + n_z * xdim11_opensbliblock00Kernel037 * ydim11_opensbliblock00Kernel037*1, xdim11_opensbliblock00Kernel037, ydim11_opensbliblock00Kernel037};
        ptr_double wk44_B0 = { wk44_B0_p + n_x*1 + n_y * xdim12_opensbliblock00Kernel037*1 + n_z * xdim12_opensbliblock00Kernel037 * ydim12_opensbliblock00Kernel037*1, xdim12_opensbliblock00Kernel037, ydim12_opensbliblock00Kernel037};
        
   OPS_ACC(wk39_B0, 0,0,0) = OPS_ACC(rhou0_B0, 0,0,0)*OPS_ACC(u2_B0, 0,0,0);

   OPS_ACC(wk40_B0, 0,0,0) = OPS_ACC(rhou1_B0, 0,0,0)*OPS_ACC(u2_B0, 0,0,0);

   OPS_ACC(wk41_B0, 0,0,0) = OPS_ACC(rho_B0, 0,0,0)*OPS_ACC(u2_B0, 0,0,0);

   OPS_ACC(wk42_B0, 0,0,0) = OPS_ACC(rhoE_B0, 0,0,0)*OPS_ACC(u2_B0, 0,0,0);

   OPS_ACC(wk43_B0, 0,0,0) = OPS_ACC(p_B0, 0,0,0)*OPS_ACC(u2_B0, 0,0,0);

   OPS_ACC(wk44_B0, 0,0,0) = OPS_ACC(rhou2_B0, 0,0,0)*OPS_ACC(u2_B0, 0,0,0);


      }
    }
  }
}
