//
// auto-generated by ops.py
//

int xdim0_opensbliblock00Kernel057;
int ydim0_opensbliblock00Kernel057;
int xdim1_opensbliblock00Kernel057;
int ydim1_opensbliblock00Kernel057;


//user function



void opensbliblock00Kernel057_c_wrapper(
  double * restrict u1_B0_p,
  double * restrict wk4_B0_p,
  int x_size, int y_size, int z_size) {
  #pragma omp parallel for
  for ( int n_z=0; n_z<z_size; n_z++ ){
    for ( int n_y=0; n_y<y_size; n_y++ ){
      for ( int n_x=0; n_x<x_size; n_x++ ){
        const ptr_double u1_B0 = { u1_B0_p + n_x*1 + n_y * xdim0_opensbliblock00Kernel057*1 + n_z * xdim0_opensbliblock00Kernel057 * ydim0_opensbliblock00Kernel057*1, xdim0_opensbliblock00Kernel057, ydim0_opensbliblock00Kernel057};
        ptr_double wk4_B0 = { wk4_B0_p + n_x*1 + n_y * xdim1_opensbliblock00Kernel057*1 + n_z * xdim1_opensbliblock00Kernel057 * ydim1_opensbliblock00Kernel057*1, xdim1_opensbliblock00Kernel057, ydim1_opensbliblock00Kernel057};
        
    OPS_ACC(wk4_B0, 0,0,0) = inv_5*(-rc13*OPS_ACC(u1_B0, 0,0,-2) + (rc8)*OPS_ACC(u1_B0, 0,0,-1) -
      rc13*OPS_ACC(u1_B0, 0,0,2) - rc14*OPS_ACC(u1_B0, 0,0,0) + (rc8)*OPS_ACC(u1_B0, 0,0,1));


      }
    }
  }
}
