//
// auto-generated by ops.py
//

int xdim0_opensbliblock00Kernel034;
int ydim0_opensbliblock00Kernel034;
int xdim1_opensbliblock00Kernel034;
int ydim1_opensbliblock00Kernel034;


//user function



void opensbliblock00Kernel034_c_wrapper(
  double * restrict rho_B0_p,
  double * restrict wk23_B0_p,
  int x_size, int y_size, int z_size) {
  #pragma omp parallel for
  for ( int n_z=0; n_z<z_size; n_z++ ){
    for ( int n_y=0; n_y<y_size; n_y++ ){
      for ( int n_x=0; n_x<x_size; n_x++ ){
        const ptr_double rho_B0 = { rho_B0_p + n_x*1 + n_y * xdim0_opensbliblock00Kernel034*1 + n_z * xdim0_opensbliblock00Kernel034 * ydim0_opensbliblock00Kernel034*1, xdim0_opensbliblock00Kernel034, ydim0_opensbliblock00Kernel034};
        ptr_double wk23_B0 = { wk23_B0_p + n_x*1 + n_y * xdim1_opensbliblock00Kernel034*1 + n_z * xdim1_opensbliblock00Kernel034 * ydim1_opensbliblock00Kernel034*1, xdim1_opensbliblock00Kernel034, ydim1_opensbliblock00Kernel034};
        
    OPS_ACC(wk23_B0, 0,0,0) = inv_1*((rc24)*OPS_ACC(rho_B0, 0,1,0) - rc21*OPS_ACC(rho_B0, 0,2,0) -
      rc23*OPS_ACC(rho_B0, 0,4,0) + (rc22)*OPS_ACC(rho_B0, 0,3,0) + (rc23)*OPS_ACC(rho_B0, 0,-4,0) -
      rc22*OPS_ACC(rho_B0, 0,-3,0) - rc24*OPS_ACC(rho_B0, 0,-1,0) + (rc21)*OPS_ACC(rho_B0, 0,-2,0));


      }
    }
  }
}
