//
// auto-generated by ops.py
//
//header
#define OPS_API 2
#define OPS_3D
#ifdef __cplusplus
#include "ops_lib_cpp.h"
#endif
#ifdef OPS_MPI
#include "ops_mpi_core.h"
#endif

#undef OPS_ACC0
#undef OPS_ACC1
#undef OPS_ACC2
#undef OPS_ACC3
#undef OPS_ACC4
#undef OPS_ACC5
#undef OPS_ACC6
#undef OPS_ACC7
#undef OPS_ACC8
#undef OPS_ACC9
#undef OPS_ACC10
#undef OPS_ACC11
#undef OPS_ACC12
#undef OPS_ACC13
#undef OPS_ACC14
#undef OPS_ACC15
#undef OPS_ACC16
// global constants
extern int block0np0;
extern int block0np1;
extern int block0np2;
extern double Delta0block0;
extern double Delta1block0;
extern double Delta2block0;
extern int niter;
extern double dt;
extern double Minf;
extern double gama;
extern double Pr;
extern double Re;
extern double inv_0;
extern double inv_1;
extern double inv_2;
extern double inv_3;
extern double inv_4;
extern double inv_5;
extern double rc6;
extern double rc7;
extern double rc8;
extern double rc9;
extern double rc10;
extern double rcinv11;
extern double rc12;
extern double rcinv13;
extern double rcinv14;
