//
// auto-generated by ops.py
//

int xdim0_opensbliblock00Kernel014;
int ydim0_opensbliblock00Kernel014;
int xdim1_opensbliblock00Kernel014;
int ydim1_opensbliblock00Kernel014;


//user function



void opensbliblock00Kernel014_c_wrapper(
  double * restrict rho_B0_p,
  double * restrict wk6_B0_p,
  int x_size, int y_size, int z_size) {
  #pragma omp parallel for
  for ( int n_z=0; n_z<z_size; n_z++ ){
    for ( int n_y=0; n_y<y_size; n_y++ ){
      for ( int n_x=0; n_x<x_size; n_x++ ){
        const ptr_double rho_B0 = { rho_B0_p + n_x*1 + n_y * xdim0_opensbliblock00Kernel014*1 + n_z * xdim0_opensbliblock00Kernel014 * ydim0_opensbliblock00Kernel014*1, xdim0_opensbliblock00Kernel014, ydim0_opensbliblock00Kernel014};
        ptr_double wk6_B0 = { wk6_B0_p + n_x*1 + n_y * xdim1_opensbliblock00Kernel014*1 + n_z * xdim1_opensbliblock00Kernel014 * ydim1_opensbliblock00Kernel014*1, xdim1_opensbliblock00Kernel014, ydim1_opensbliblock00Kernel014};
        
    OPS_ACC(wk6_B0, 0,0,0) = inv_0*((rc24)*OPS_ACC(rho_B0, 1,0,0) - rc21*OPS_ACC(rho_B0, 2,0,0) -
      rc23*OPS_ACC(rho_B0, 4,0,0) + (rc22)*OPS_ACC(rho_B0, 3,0,0) + (rc23)*OPS_ACC(rho_B0, -4,0,0) -
      rc22*OPS_ACC(rho_B0, -3,0,0) - rc24*OPS_ACC(rho_B0, -1,0,0) + (rc21)*OPS_ACC(rho_B0, -2,0,0));


      }
    }
  }
}
