//
// auto-generated by ops.py
//

int xdim0_opensbliblock00Kernel016;
int ydim0_opensbliblock00Kernel016;
int xdim1_opensbliblock00Kernel016;
int ydim1_opensbliblock00Kernel016;


//user function



void opensbliblock00Kernel016_c_wrapper(
  double * restrict rhou1_B0_p,
  double * restrict wk8_B0_p,
  int x_size, int y_size, int z_size) {
  #pragma omp parallel for
  for ( int n_z=0; n_z<z_size; n_z++ ){
    for ( int n_y=0; n_y<y_size; n_y++ ){
      for ( int n_x=0; n_x<x_size; n_x++ ){
        const ptr_double rhou1_B0 = { rhou1_B0_p + n_x*1 + n_y * xdim0_opensbliblock00Kernel016*1 + n_z * xdim0_opensbliblock00Kernel016 * ydim0_opensbliblock00Kernel016*1, xdim0_opensbliblock00Kernel016, ydim0_opensbliblock00Kernel016};
        ptr_double wk8_B0 = { wk8_B0_p + n_x*1 + n_y * xdim1_opensbliblock00Kernel016*1 + n_z * xdim1_opensbliblock00Kernel016 * ydim1_opensbliblock00Kernel016*1, xdim1_opensbliblock00Kernel016, ydim1_opensbliblock00Kernel016};
        
    OPS_ACC(wk8_B0, 0,0,0) = inv_0*(-rc7*OPS_ACC(rhou1_B0, 2,0,0) + (rc7)*OPS_ACC(rhou1_B0, -2,0,0) -
      rc8*OPS_ACC(rhou1_B0, -1,0,0) + (rc8)*OPS_ACC(rhou1_B0, 1,0,0));


      }
    }
  }
}
