//
// auto-generated by ops.py
//

int xdim0_opensbliblock00Kernel078;
int ydim0_opensbliblock00Kernel078;
int xdim1_opensbliblock00Kernel078;
int ydim1_opensbliblock00Kernel078;


//user function



void opensbliblock00Kernel078_c_wrapper(
  double * restrict u0_B0_p,
  double * restrict wk25_B0_p,
  int x_size, int y_size, int z_size) {
  #pragma omp parallel for
  for ( int n_z=0; n_z<z_size; n_z++ ){
    for ( int n_y=0; n_y<y_size; n_y++ ){
      for ( int n_x=0; n_x<x_size; n_x++ ){
        const ptr_double u0_B0 = { u0_B0_p + n_x*1 + n_y * xdim0_opensbliblock00Kernel078*1 + n_z * xdim0_opensbliblock00Kernel078 * ydim0_opensbliblock00Kernel078*1, xdim0_opensbliblock00Kernel078, ydim0_opensbliblock00Kernel078};
        ptr_double wk25_B0 = { wk25_B0_p + n_x*1 + n_y * xdim1_opensbliblock00Kernel078*1 + n_z * xdim1_opensbliblock00Kernel078 * ydim1_opensbliblock00Kernel078*1, xdim1_opensbliblock00Kernel078, ydim1_opensbliblock00Kernel078};
        
    OPS_ACC(wk25_B0, 0,0,0) = inv_5*(-rc21*OPS_ACC(u0_B0, 0,0,2) - rc28*OPS_ACC(u0_B0, 0,0,-4) +
      (rc25)*OPS_ACC(u0_B0, 0,0,1) - rc28*OPS_ACC(u0_B0, 0,0,4) - rc26*OPS_ACC(u0_B0, 0,0,0) -
      rc21*OPS_ACC(u0_B0, 0,0,-2) + (rc27)*OPS_ACC(u0_B0, 0,0,3) + (rc27)*OPS_ACC(u0_B0, 0,0,-3) +
      (rc25)*OPS_ACC(u0_B0, 0,0,-1));


      }
    }
  }
}
