//
// auto-generated by ops.py
//

int xdim0_opensbliblock00Kernel056;
int ydim0_opensbliblock00Kernel056;
int xdim1_opensbliblock00Kernel056;
int ydim1_opensbliblock00Kernel056;


//user function



void opensbliblock00Kernel056_c_wrapper(
  double * restrict wk15_B0_p,
  double * restrict wk3_B0_p,
  int x_size, int y_size, int z_size) {
  #pragma omp parallel for
  for ( int n_z=0; n_z<z_size; n_z++ ){
    for ( int n_y=0; n_y<y_size; n_y++ ){
      for ( int n_x=0; n_x<x_size; n_x++ ){
        const ptr_double wk15_B0 = { wk15_B0_p + n_x*1 + n_y * xdim0_opensbliblock00Kernel056*1 + n_z * xdim0_opensbliblock00Kernel056 * ydim0_opensbliblock00Kernel056*1, xdim0_opensbliblock00Kernel056, ydim0_opensbliblock00Kernel056};
        ptr_double wk3_B0 = { wk3_B0_p + n_x*1 + n_y * xdim1_opensbliblock00Kernel056*1 + n_z * xdim1_opensbliblock00Kernel056 * ydim1_opensbliblock00Kernel056*1, xdim1_opensbliblock00Kernel056, ydim1_opensbliblock00Kernel056};
        
    OPS_ACC(wk3_B0, 0,0,0) = inv_1*(-rc13*OPS_ACC(wk15_B0, 0,2,0) + (rc13)*OPS_ACC(wk15_B0, 0,-2,0) -
      rc12*OPS_ACC(wk15_B0, 0,-1,0) + (rc12)*OPS_ACC(wk15_B0, 0,1,0));


      }
    }
  }
}
