//
// auto-generated by ops.py
//

int xdim0_opensbliblock00Kernel080;
int ydim0_opensbliblock00Kernel080;
int xdim1_opensbliblock00Kernel080;
int ydim1_opensbliblock00Kernel080;
int xdim2_opensbliblock00Kernel080;
int ydim2_opensbliblock00Kernel080;


//user function



void opensbliblock00Kernel080_c_wrapper(
  double * restrict rho_B0_p,
  double * restrict p_B0_p,
  double * restrict T_B0_p,
  int x_size, int y_size, int z_size) {
  #pragma omp parallel for
  for ( int n_z=0; n_z<z_size; n_z++ ){
    for ( int n_y=0; n_y<y_size; n_y++ ){
      for ( int n_x=0; n_x<x_size; n_x++ ){
        const ptr_double rho_B0 = { rho_B0_p + n_x*1 + n_y * xdim0_opensbliblock00Kernel080*1 + n_z * xdim0_opensbliblock00Kernel080 * ydim0_opensbliblock00Kernel080*1, xdim0_opensbliblock00Kernel080, ydim0_opensbliblock00Kernel080};
        const ptr_double p_B0 = { p_B0_p + n_x*1 + n_y * xdim1_opensbliblock00Kernel080*1 + n_z * xdim1_opensbliblock00Kernel080 * ydim1_opensbliblock00Kernel080*1, xdim1_opensbliblock00Kernel080, ydim1_opensbliblock00Kernel080};
        ptr_double T_B0 = { T_B0_p + n_x*1 + n_y * xdim2_opensbliblock00Kernel080*1 + n_z * xdim2_opensbliblock00Kernel080 * ydim2_opensbliblock00Kernel080*1, xdim2_opensbliblock00Kernel080, ydim2_opensbliblock00Kernel080};
        
   OPS_ACC(T_B0, 0,0,0) = pow(Minf, 2)*gama*OPS_ACC(p_B0, 0,0,0)/OPS_ACC(rho_B0, 0,0,0);


      }
    }
  }
}
